# Generated by Django 2.2 on 2020-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0003_auto_20200902_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('BillName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=100)),
                ('CartPrice', models.CharField(max_length=10)),
                ('product', models.ManyToManyField(to='EmailApp.Product')),
            ],
        ),
    ]
