# Generated by Django 2.2 on 2020-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0006_auto_20200918_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Discount',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='Taxes',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.CharField(default='', max_length=10),
        ),
    ]
