# Generated by Django 2.2 on 2020-09-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0007_auto_20200922_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.CharField(choices=[('wish', 'wish'), ('unwished', 'unwished')], default='unwished', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailApp.Product')),
            ],
        ),
    ]
