# Generated by Django 2.2 on 2020-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0008_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
