# Generated by Django 2.2 on 2020-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0009_auto_20200922_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'Process'), ('PENDING', 'Pending'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=20),
        ),
    ]
